all:

	gcc -o lab6.o -c lab6.c
	gcc -o bitset.o -c bitset.c
	gcc -g bitset.o lab6.o -o bits

debug:

	gcc -o lab6.o -c lab6.c
	gcc -o bitset.o -c bitset.c
	gcc -g bitset.o lab6.o -o bits

clean:
	rm ./bitset.o
	rm ./lab6.o
	rm ./bits

