all:
	g++ -o output ../utilities.cpp postboxes.cpp -I /usr/include/opencv -L /usr/lib -lm -lcv -lhighgui -lcvaux

debug:
	g++ -g -o output ../utilities.cpp postboxes.cpp -I /usr/include/opencv -L /usr/lib -lm -lcv -lhighgui -lcvaux


paul:
	g++ -o paul ../utilities.cpp postboxesPaul.cpp -I /usr/include/opencv -L /usr/lib -lm -lcv -lhighgui -lcvaux


