all:
	g++ -o output ../utilities.cpp surveillance.cpp -I /usr/include/opencv -L /usr/lib -lm -lcv -lhighgui -lcvaux

debug:
	g++ -g -o output ../utilities.cpp surveillance.cpp -I /usr/include/opencv -L /usr/lib -lm -lcv -lhighgui -lcvaux
